### ISSUE TITLE
License

### ISSUE THREAD

**Issue by curran** [holtzy/react-graph-gallery#20]
I'm curious what open source license is this released under, if any?

I checked for a `LICENSE` file and in `package.json` but did not find any license.

It would be awesome to clarify the license. MIT or ISC would be a great fit I think.

Thank you for this amazing work!

**Comment by curran** [comment]
Oh, just add a new file at the top level of the repository called `LICENSE` (with no file extension) that has the following text:

```
Copyright 2023 Yan Holz

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

This text comes from https://opensource.org/license/isc-license-txt/

This is the ISC license, which is a pretty standard permissive licence which is pretty much the same as the MIT license but with less words.

Also adding a `license` field to `package.json` would reinforce that within NPM.

**Comment by holtzy** [comment]
Thank you SO MUCH for your help on this. This is very very very much appreciated 🙏🙏🙏🙏
