### ISSUE TITLE
ChartOrSandbox doesn't match?

### ISSUE THREAD

**Issue by tallowen** [holtzy/react-graph-gallery#25]
In the section "Line chart application" of timeseries, it looks like the ChartOrSandbox isn't rendering the same thing between the chart and when actually opening up the sandbox:

Without sandbox open (time series):
<img width="924" alt="Screenshot 2024-03-29 at 2 37 22 PM" src="https://github.com/holtzy/react-graph-gallery/assets/557689/de225767-030a-47d0-9717-e9e9eca21227">

With sandbox open (group demo):
<img width="1301" alt="Screenshot 2024-03-29 at 2 37 41 PM" src="https://github.com/holtzy/react-graph-gallery/assets/557689/40dfc8f8-52b1-4cb7-ab6b-0d4c1f7d69d6">

Apologies in advanced if this was expected!

**Comment by holtzy** [comment]
Thanks a lot, should be fixed now 🙏
